marfatech_rabbit_queue:
    connections:
        default:
            host: '%env(resolve:RABBITMQ_HOST)%'
            port: '%env(int:RABBITMQ_PORT)%'
            username: '%env(resolve:RABBITMQ_USER)%'
            password: '%env(resolve:RABBITMQ_PASSWORD)%'
            vhost: '%env(resolve:RABBITMQ_DEFAULT_VHOST)%'
            connection_timeout: 120
            read_write_timeout: 600
            heartbeat: 300
