my_builder_cronos:
    exporter:
        key:        '%env(string:PROJECT_NAME)%'
        mailto:     '%env(string:CRON_MAILTO)%'
        executor:   '%env(string:CRON_PHP_EXECUTOR)%'
        console:    '%kernel.project_dir%/bin/console'
        shell:      '%env(string:CRON_SHELL)%'
