security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Admin:
            algorithm: auto

    providers:
        admin:
            entity:
                class: App\Entity\Admin
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
                always_use_default_target_path: true
            logout:
                path: /admin/logout
                target: /admin/login

    access_control:
        - { path: ^/admin/login, roles: !php/const Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter::PUBLIC_ACCESS }
        - { path: ^/admin, roles: !php/const App\Enum\AdminRoleEnum::ROLE_ADMIN }
        - { path: ^/backofficeapi/auth/login, roles: PUBLIC_ACCESS }
