monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels:
                - '!event'
        console:
            type: console
            process_psr_3_messages: false
            channels:
                - '!event'
                - '!doctrine'
                - '!console'
        grouped:
            type: whatfailuregroup
            members:
                - 'graylog'
            channels:
                - '!php'
        graylog:
            type: gelf
            publisher:
                hostname: '%env(resolve:GRAYLOG_HOST)%'
                port: 12201
            level: warning
