#!/bin/sh
source .env
echo -e \
"APP_ENV=$APP_ENV\n\
DOMAIN=$DOMAIN\n\
APP_DEBUG=$APP_DEBUG\n\
MYSQL_BIREPORT_HOST=$MYSQL_BIREPORT_HOST\n\
MYSQL_BIREPORT_USER=$MYSQL_BIREPORT_USER\n\
MYSQL_BIREPORT_PASSWORD=$MYSQL_BIREPORT_PASSWORD\n\
MYSQL_BIREPORT_DATABASE=$MYSQL_BIREPORT_DATABASE\n\
DATABASE_BIREPORT_URL=//$MYSQL_BIREPORT_USER:$MYSQL_BIREPORT_PASSWORD@$MYSQL_BIREPORT_HOST:3306/$MYSQL_BIREPORT_DATABASE\n\
GRAYLOG_HOST=$GRAYLOG_HOST\n\
CLICKHOUSE_HOST=$CLICKHOUSE_HOST\n\
CLICKHOUSE_USER=$CLICKHOUSE_USER\n\
CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD\n\
CLICKHOUSE_DATABASE=$CLICKHOUSE_DATABASE\n\
" >> .env.local
exec "$@"