---
-
    name: '{{ marfatech_deploy_from_branch }} | Replace supervisor config path'
    replace:
        path: '{{ ansistrano_release_path.stdout }}/config/supervisor/{{ symfony_env }}/supervisor.conf'
        regexp: '__MARFATECH_RELEASE_CONSOLE_PATH__'
        replace: '{{ marfatech_release_console_path }}'
-
    name: '{{ marfatech_deploy_from_branch }} | Add {{ marfatech_project_name }} to supervisor program name'
    replace:
        path: '{{ ansistrano_release_path.stdout }}/config/supervisor/{{ symfony_env }}/supervisor.conf'
        regexp: '^\[program:'
        replace: '[program:{{ marfatech_project_name }}-{{ symfony_env }}-'
