-
    name:           DEV-STAGE deployment script
    hosts:          dev-stage
    remote_user:    deployer
    become_user:    deployer
    gather_facts:   false

    roles:
        - cbrunnkvist.ansistrano-symfony-deploy

    vars:
        # custom
        marfatech_deploy_from_branch:       '{{ branch }}'
        marfatech_release_console_path:     '{{ ansistrano_release_path.stdout }}/{{symfony_console_path}}'

        # ansistrano
        ansistrano_git_repo:                '{{ marfatech_git_repo }}'
        ansistrano_deploy_via:              git
        ansistrano_current_dir:             current
        ansistrano_allow_anonymous_stats:   false
        ansistrano_deploy_to:               '{{ study_deploy_to }}'
        ansistrano_git_branch:              '{{ marfatech_deploy_from_branch }}'
        ansistrano_keep_releases:           5
        ansistrano_shared_paths:
            - 'var/log'
            - 'public/images'
            - 'storage'
            - 'parameters'
        ansistrano_shared_files:
            - '.env.local'

        # symfony deployer
        symfony_env:                        dev
        symfony_php_path:                   php
        symfony_run_composer:               true
        symfony_composer_options:           '-v -n -o --prefer-dist --no-progress'
        symfony_console_path:               'bin/console'
        symfony_run_assetic_dump:           false
        symfony_run_doctrine_migrations:    true
        symfony_doctrine_options:           '--no-interaction'
        symfony_composer_version:           2.0.9

        # hooks
#        ansistrano_before_symlink_shared_tasks_file: '{{ playbook_dir }}/hook_dev-stage/before-symlink-shared-tasks-file.yaml'
#        ansistrano_after_symlink_tasks_file: '{{ playbook_dir }}/hook_dev-stage/after-symlink-tasks-file.yaml'
