name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/authorized_keys"
      - run: chmod 600 "$HOME/.ssh/authorized_keys"
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/authorized_keys -o StrictHostKeyChecking=no" --archive --compress --delete . root@45.12.238.189:/var/www/symfony
